In [8]:
import numpy as np
A = [[10,6],[6,5]]
np.array(A)
np.linalg.eig(A)

(array([14.,  1.]),
 array([[ 0.83205029, -0.5547002 ],
        [ 0.5547002 ,  0.83205029]]))

In [10]:
A2 = [[0,1,3],[1,0,2]]
np.array(A2)
np.linalg.svd(A2)

(array([[-0.83205029, -0.5547002 ],
        [-0.5547002 ,  0.83205029]]),
 array([3.74165739, 1.        ]),
 array([[-1.48249863e-01, -2.22374795e-01, -9.63624112e-01],
        [ 8.32050294e-01, -5.54700196e-01, -8.32667268e-17],
        [-5.34522484e-01, -8.01783726e-01,  2.67261242e-01]]))

In [5]:
a = 1
b = 2
c = 1

delta = (b*b) - (4*a*c)
bhaskara1 = (-b + ((delta)**(1/2)))/2*a
bhaskara2 = (-b - ((delta)**(1/2)))/2*a
print(delta,bhaskara1, bhaskara2)

0 -1.0 -1.0
